version: '3.5'
services:
    test-node01-te:
        container_name: test-node01-te
        hostname: test-node01-te
        image: mysql/mysql-server:5.7
        networks: 
            cluster-network:
        expose: 
            - "3306"
        env_file: 
            - ./conf/db.env
        volumes: 
            - "./conf/node01/my.cnf:/etc/my.cnf"
            - "node01:/var/lib/mysql"
            - "./scripts/master/:/docker-entrypoint-initdb.d"

    test-node02-te:
        container_name: test-node02-te
        hostname: test-node02-te
        image: mysql/mysql-server:5.7
        networks: 
            cluster-network:
        expose: 
            - "3306"
        env_file: 
            - ./conf/db.env
        volumes: 
            - "./conf/node02/my.cnf:/etc/my.cnf"
            - "node02:/var/lib/mysql"
            - "./scripts/slaves/:/docker-entrypoint-initdb.d"
            - "./scripts/tools/:/usr/local/bin"
        depends_on: 
            - test-node01-te
        command: ["wait-for-it.sh", "test-node01-te:3306","--timeout=80", "--strict", "--", "/entrypoint.sh", "mysqld"]

    test-node03-pa:
        container_name: test-node03-pa
        hostname: test-node03-pa
        image: mysql/mysql-server:5.7
        networks: 
            cluster-network:
        expose: 
            - "3306"
        env_file: 
            - ./conf/db.env
        volumes: 
            - "./conf/node03/my.cnf:/etc/my.cnf"
            - "node03:/var/lib/mysql"
            - "./scripts/slaves/:/docker-entrypoint-initdb.d"
            - "./scripts/tools/:/usr/local/bin"
        depends_on: 
            - test-node01-te
        command: ["wait-for-it.sh", "test-node01-te:3306","--timeout=80", "--strict", "--", "/entrypoint.sh", "mysqld"]

    orchestrator1:
        container_name: orchestrator1
        image: orchestrator
        networks: 
            cluster-network:
        expose:
            - "3000"
        ports: 
            - "3001:3000"            
        volumes: 
            - "./conf/node01/orchestrator.conf.json:/etc/orchestrator.conf.json"
            - "./scripts/tools/:/usr/local/bin"
        command: ["wait-for-it.sh", "test-node01-te:3306","--timeout=80", "--strict", "--", "/entrypoint.sh"]

    orchestrator2:
        container_name: orchestrator2
        image: orchestrator
        networks: 
            cluster-network:
        expose:
            - "3000"
        ports: 
            - "3002:3000"            
        volumes: 
            - "./conf/node02/orchestrator.conf.json:/etc/orchestrator.conf.json"
            - "./scripts/tools/:/usr/local/bin"
        command: ["wait-for-it.sh", "test-node01-te:3306","--timeout=80", "--strict", "--", "/entrypoint.sh"]

    orchestrator3:
        container_name: orchestrator3
        image: orchestrator
        networks: 
            cluster-network:
        expose:
            - "3000"
        ports: 
            - "3003:3000"            
        volumes: 
            - "./conf/node03/orchestrator.conf.json:/etc/orchestrator.conf.json"
            - "./scripts/tools/:/usr/local/bin"
        command: ["wait-for-it.sh", "test-node01-te:3306","--timeout=80", "--strict", "--", "/entrypoint.sh"]    

    haproxy:
        image: haproxy:1.8
        depends_on:
            - orchestrator1
            - orchestrator2
            - orchestrator3
        ports:
            - 80:80
        volumes:
            - "./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
        networks:
            cluster-network:
        
networks: 
    cluster-network:
        name: clusterDR
volumes: 
    node01:
    node02:
    node03:
